before:
  hooks:
    - sh -c "go run . _gendoc --man | gzip > rare.1.gz"

# Make sure to check the documentation at http://goreleaser.com
builds:
- id: rare-pcre
  binary: rare-pcre
  env:
    - CGO_ENABLED=1
  flags:
    - -trimpath
  tags:
    - pcre2
    - urfave_cli_no_docs
    - rare_no_pprof
  ldflags:
    - -s -w
    - -X main.version={{.Version}}
    - -X main.buildSha={{.ShortCommit}}
  goarch:
    - amd64
  goos:
    - linux
- id: rare
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  tags:
    - urfave_cli_no_docs
    - rare_no_pprof
  ldflags:
    - -s -w
    - -X main.version={{.Version}}
    - -X main.buildSha={{.ShortCommit}}
  goarch:
    - amd64
    - arm64
  goos:
    - linux
    - darwin
    - windows

archives:
- allow_different_binary_count: true
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE*
    - README*
    - rare.1.gz

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://github.com/zix99/rare
    description: Realtime regex-extraction and aggregation into common formats such as histograms, bar graphs, numerical summaries, tables, and more!
    maintainer: Christopher LaPointe (chris@zdyn.net)
    license: GPLv3
    vendor: zix99
    formats:
    - deb
    - rpm
    - apk
    dependencies:
    - libpcre2-8-0
    contents:
    - src: ./rare.1.gz
      dst: /usr/share/man/man1/rare.1.gz

brews:
- tap:
    owner: zix99
    name: homebrew-rare
  commit_author:
    name: rare-bot
    email: noreply@zdyn.net
  homepage: https://github.com/zix99/rare
  description: Fast, realtime regex-extraction, and aggregation into common formats such as histograms, numerical summaries, tables, and more!
  install: |
    bin.install "rare"
    man1.install Dir["rare.1.gz"]
  test: |
    system "#{bin}/rare -v"
